### PR TITLE
Import only needed upto 2.5

### PR DESCRIPTION
**Pull request by wilsonge**

### CODE REVIEW

**Comment by betweenbrain** [comment]
Thanks @wilsonge!

**Comment by wilsonge** [comment]
We need to extend this over all stages and for all models view and controllers btw. I noticed this one before noticing it was everywhere :P

**Comment by betweenbrain** [comment]
Very true. The entire thing needs a lot of love :-)

Best,

Matt Thomas
203.632.9322
http://betweenbrain.com/

**Comment by wilsonge** [comment]
So true!

**Pull request merged**
